apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.branch }}.streamlit.aaronbatilo.dev
  gateways:
    - streamlit-preview
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "chart.fullname" . }}
