name: Pull Request Opened
on:
  pull_request:
    types:
      - opened

jobs:
  opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: "no"
      - name: Deploy preview environment
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH="${REF##*/}" # Keep only branch name
          helm -n streamlit-preview upgrade --install "streamlit-preview-${BRANCH}" deployments/chart --set branch="${BRANCH}"
