name: Pull Request Opened
on:
  pull_request:
    # types:
    #   - opened

jobs:
  opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Filter out unneeded dependencies"
        run: |
          cat .tool-versions | grep -vE "golang|nodejs|poetry|pulumi|python" > .filtered
          mv .filtered .tool-versions
      - uses: asdf-vm/actions/install@v1
        env:
          NODEJS_CHECK_SIGNATURES: "no"
      - name: Deploy preview environment
        env:
          BRANCH: ${{ github.head_ref }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
        run: |
          # Get EKS credentials
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}
          helm -n streamlit-preview upgrade --install "${BRANCH}" deployments/chart --set branch="${BRANCH}"
      - name: Comment PR URL
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.head_ref }}
        with:
          check_for_duplicate_msg: true
          msg: |
            View your PR in action by going to [https://${{ github.head_ref }}.streamlit.aaronbatilo.dev](https://${{ github.head_ref }}.streamlit.aaronbatilo.dev)
