name: Publish Reloader
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.0"

      - name: Cache Docker layers
        id: cache-docker
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u abatilo --password-stdin

      - name: Build and push
        if: steps.cache-docker.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/streamlit-reloader:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          context: .
          file: ./build/Dockerfile
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/streamlit-preview-environments-demo
